apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: tailscale-webhook
  labels:
    app: tailscale-webhook
webhooks:
- name: tailscale-injector.tailscale.com
  admissionReviewVersions: ["v1", "v1beta1"]
  clientConfig:
    service:
      name: tailscale-webhook
      namespace: tailscale
      path: "/mutate"
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUROekNDQWgrZ0F3SUJBZ0lVWUNHVFFha0t2VUNNbk8vZmxZOTlPV3o5ZGNJd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0tqRW9NQ1lHQTFVRUF3d2ZkR0ZwYkhOallXeGxMWGRsWW1odmIyc3VkR0ZwYkhOallXeGxMbk4yWXpBZwpGdzB5TlRFeE1Ua3dNVE0wTVRWYUdBOHlNRFV6TURRd05qQXhNelF4TlZvd0tqRW9NQ1lHQTFVRUF3d2ZkR0ZwCmJITmpZV3hsTFhkbFltaHZiMnN1ZEdGcGJITmpZV3hsTG5OMll6Q0NBU0l3RFFZSktvWklodmNOQVFFQkJRQUQKZ2dFUEFEQ0NBUW9DZ2dFQkFNOU55Y1pxdEsxQk5DM1RRaEZTbFM1Y21mSHB1VG1jMmNxY284WDVIMi9JYTk1aApkNUVUUVgvL3VUSE1lZ2xYWWtXYlF1aVFhbFRxUlVRckQ3MzhxR0VPTmU2YXBnZE5CUFd1Y0ROMEZTcm95MlVDCmNKT0lnUlJyM1RURGFEMEhoNG82OGZIcW51ZmpJRGJIQXBqSXp2bElXUWVieHQwOEM0d3NKenpLQmJ1MDFZdFAKTTBPMlFBMW16c2hnclh0ZzgzMjVrelhSV0JxSSttaXpydE5SRlh1QlFqU1ZyWURvU2dKZmc0U3Q0eFBJMDd4SQp0TWhkN0tuaWZvTjBBZittUm55OW4vbTVORkxHc21ZSUJLU09xcXhweGJ5aFY5bGloV3dERnZIWW5RMWhidUh2CkRlV1o5V0NPZjVEaXd4NnRlNGxuSzlPYlpma0dxUGhOdVhzTit1Y0NBd0VBQWFOVE1GRXdIUVlEVlIwT0JCWUUKRkI2QUUvaGxmS2JqSFNiZ1ptMXhwN0FpWTZtcU1COEdBMVVkSXdRWU1CYUFGQjZBRS9obGZLYmpIU2JnWm0xeApwN0FpWTZtcU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFENW5xdnVwCllkUEl2NDVVb2xBSTVzNUR0NWpIL21HUzJEeVlzQ1h0ZjBNOVhKUGpBTVJNSHRQV2RFd0lKTkM2cHBDYklRbmEKUVF4WGdlSGpnUjBkR1ZZUFlyblRvTG1BZ1c1WXBMTG11UzUwTWVnWXcvQXJmWFBEQmkrOHFWSUl1eGNqbmlQWgpibXNjU29jeHNFR2M4OGRYZ0xDZWhzamppVkVSYytPR3JnblZuaWJwOFFvL0pxaG1vdERSNzM0MEYrRThMeFBRCkFJOG0reDNFNDE3NjkzUkhROXJYK2ZIS2xKVkxWYWsrb0Y1bWZ2dmhqQjJaQXIyV0RET3QrK1NOV293eXJKajkKMkkzMWN4a1djNmJwTFJELzM3cTIwT1ozMmZjNlY1d2RRTGZNaWlORld0Y0doQURWVFVlWDhoRWJERXdxUll6VApmZHFRMStBeHpkQXlDSWs9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  rules:
  - operations: ["CREATE"]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
  failurePolicy: Fail
  sideEffects: None
  namespaceSelector:
    matchExpressions:
    - key: tailscale.com/inject
      operator: NotIn
      values: ["disabled"]
  objectSelector:
    matchLabels:
      tailscale.com/inject: "true"

